### ISSUE TITLE
ConstraintHint object is not accessible when resizing

### ISSUE THREAD

**Issue by subzerobo** [imazen/imageflow-go#1]
Hi

Thank you for this great binding for Golang.

I don't know if I am looking somewhere wrong or it is not possible to pass down constrain info to the Constrain methods in steps, currently, only ConstrainWithin, ConstrainWithinW, and ConstrainWithinH are exported and there is no way to pass the ConstraintHint to these methods to be effective when calling them.

https://github.com/imazen/imageflow-go/blob/63f4406220136056912ed5efbed7c0c8e62d531f/imageflow.go#L48

**Comment by anshulrgoyal** [comment]
Hi @subzerobo 
Thanks for pointing out. I will add the method and update binding in few hours :).

**Comment by anshulrgoyal** [comment]
I updated code to expose `Constrain` function.
