### ISSUE TITLE
Watermark opacity parameter not working

### ISSUE THREAD

**Issue by PieroValdebenito** [imazen/imageflow-go#3]
It looks like the variable is not being passed to the struct, also hints variable

https://github.com/imazen/imageflow-go/blob/main/imageflow.go#L229

**Comment by lilith** [comment]
Thanks for reporting this! @anshulrgoyal

**Comment by anshulrgoyal** [comment]
thanks @PieroValdebenito I will fix this

**Comment by anshulrgoyal** [comment]
@PieroValdebenito This is fixed. Thanks for pointing it out.
