### ISSUE TITLE
corss-compile  error： `undefined: newJob`

### ISSUE THREAD

**Issue by lanink** [imazen/imageflow-go#5]
I tried to cross-compile to Windows or Linux on MAC, but it didn't work。

` ../../../.go/pkg/mod/github.com/imazen/imageflow-go@v0.0.0-20210701065632-6277a99a1eec/imageflow.go:145:9: undefined: newJob`

what should I do？

**Comment by anshulrgoyal** [comment]
I think u r not doing go mod vendor with GOOS and GOARCH variables for cross compilation
