### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by SeaaaaaSharp** [imazen/imageflow-go#7]
Greetings, I'm not completly certain this is the library's fault or not, but when running this piece of code for an extended period of time the memory doesn't seem to shrink and keeps on growing. The code in question starts **jobCount** goroutines, each one adjust brightness and writes the result to /dev/null for testing, when they're all done the loop repeats itself, when running this for a few minutes the process gets killed with OOM error.

https://gist.github.com/SeaaaaaSharp/91f8146699e1cc86d61168496464a182

**Comment by SeaaaaaSharp** [comment]
@anshulrgoyal Could you please take a look?

**Comment by SeaaaaaSharp** [comment]
@lilith

**Comment by anshulrgoyal** [comment]
I think I found the issue. go will not gc types like Cbytes etc.
